import {readFile, writeFile} from 'node:fs/promises';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import ts from 'typescript';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..');
const sourcePath = resolve(repoRoot, 'response-review/web/app.ts');
const outputPath = resolve(repoRoot, 'response-review/web/app.js');

const source = await readFile(sourcePath, 'utf8');
const transpiled = ts.transpileModule(source, {
  compilerOptions: {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.None,
    newLine: ts.NewLineKind.LineFeed,
    removeComments: false,
  },
  fileName: sourcePath,
});

const header = '// Generated from response-review/web/app.ts. Do not edit this file directly.\n';
await writeFile(outputPath, `${header}${transpiled.outputText}`, 'utf8');
