import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import {
  ensureResponseReviewWebBundle,
  getResponseReviewWebBundlePaths,
  transpileResponseReviewWebSource,
} from '../scripts/web-bundle.mjs';
import {buildResponseReviewHtml} from '../src/ui.ts';

test('web bundle generation adds a clear generated-artifact header', () => {
  const output = transpileResponseReviewWebSource('const value: number = 1;\n');

  assert.match(
    output,
    /^\/\/ Generated from response-review\/web\/app\.ts\. Do not edit this file directly\./,
  );
  assert.match(output, /const value = 1;/);
});

test('buildResponseReviewHtml inlines escaped data and generated app script', () => {
  ensureResponseReviewWebBundle({rebuildIfStale: true});

  const html = buildResponseReviewHtml({
    session: {
      kind: 'current',
      sessionId: 'session-1',
      sessionPath: null,
      cwd: '/repo',
      name: null,
      displayTitle: '<dangerous>& session',
    },
    responses: [],
  });

  assert.equal(html.includes('__INLINE_DATA__'), false);
  assert.equal(html.includes('__INLINE_JS__'), false);
  assert.match(html, /\\u003cdangerous\\u003e\\u0026 session/);
  assert.match(html, /Generated from response-review\/web\/app\.ts/);
});

test('ensureResponseReviewWebBundle rebuilds a missing generated artifact', t => {
  const {outputPath} = getResponseReviewWebBundlePaths();
  const original = fs.existsSync(outputPath)
    ? fs.readFileSync(outputPath, 'utf8')
    : null;

  t.after(() => {
    if (original !== null) {
      fs.writeFileSync(outputPath, original, 'utf8');
    } else if (fs.existsSync(outputPath)) {
      fs.rmSync(outputPath);
    }
  });

  if (fs.existsSync(outputPath)) {
    fs.rmSync(outputPath);
  }

  ensureResponseReviewWebBundle();

  assert.equal(fs.existsSync(outputPath), true);
  assert.match(
    fs.readFileSync(outputPath, 'utf8'),
    /^\/\/ Generated from response-review\/web\/app\.ts\. Do not edit this file directly\./,
  );
});
